[package]
name = "xswezan/modernplayerlist"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Janitor = "howmanysmall/janitor@1.15.1"
# Promise = "evaera/promise@4.0.0"
Fusion = "elttob/fusion@0.2.0"
TableUtil = "sleitnick/table-util@1.2.1"

[dev-dependencies]
Fitumi = "bytebit/fitumi@1.0.11"